name: snake

on:
  schedule:
    - cron: "0 */1 * * *" 
  
  workflow_dispatch:
jobs:
  generate:
    permissions: 
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: generate github-contribution-snake.svg
        uses: Platane/snk/svg-only@v3.2.0
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/github-contribution-snake.svg
            dist/github-contribution-snake.svg?palette=github&color_dots=#d7cfe6,#c0a1ff,#8e6aeb,#8349f5,#6421eb&color_snake=#5500ff&color_background=#ffffff
          
      - name: push github-contribution-snake.svg to the output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}